#include "NativeNetwork.hpp"
#include <xtl.h>
#include <xhttp.h>
#include <cstdio>

namespace sd360x {
bool networkStart(){XNetStartupParams xp;ZeroMemory(&xp,sizeof(xp));xp.cfgSizeOfStruct=sizeof(xp);if(XNetStartup(&xp)!=0)return false;WSADATA w;return WSAStartup(MAKEWORD(2,2),&w)==0;}
static bool crack(const std::string& u,XHTTP_URL_COMPONENTS& c,char* host,DWORD hn,char* path,DWORD pn){ZeroMemory(&c,sizeof(c));c.dwStructSize=sizeof(c);c.lpszHostName=host;c.dwHostNameLength=hn;c.lpszUrlPath=path;c.dwUrlPathLength=pn;return XHttpCrackUrl(u.c_str(),u.size(),0,&c)!=FALSE;}
bool httpGetText(const std::string& u,std::string& out){out.clear();char host[256]={0},path[1024]={0};XHTTP_URL_COMPONENTS c;if(!crack(u,c,host,255,path,1023))return false;HINTERNET s=XHttpOpen("SeriesDash360/1.0",XHTTP_ACCESS_TYPE_NO_PROXY,0,0,0);if(!s)return false;DWORD flags=(c.nScheme==INTERNET_SCHEME_HTTPS)?XHTTP_FLAG_SECURE:0;HINTERNET con=XHttpConnect(s,host,c.nPort,flags);if(!con){XHttpCloseHandle(s);return false;}HINTERNET r=XHttpOpenRequest(con,"GET",path,0,0,0,0);bool ok=false;if(r&&XHttpSendRequest(r,0,0,0,0,0,0)&&XHttpReceiveResponse(r,0)){char b[4096];DWORD n=0;do{n=0;if(!XHttpReadData(r,b,sizeof(b),&n))break;if(n)out.append(b,n);}while(n);ok=!out.empty();}if(r)XHttpCloseHandle(r);XHttpCloseHandle(con);XHttpCloseHandle(s);return ok;}
bool httpDownloadFile(const std::string& u,const std::string& p){std::string d;if(!httpGetText(u,d))return false;HANDLE h=CreateFileA(p.c_str(),GENERIC_WRITE,0,0,CREATE_ALWAYS,0,0);if(h==INVALID_HANDLE_VALUE)return false;DWORD n=0;BOOL ok=WriteFile(h,d.data(),d.size(),&n,0);CloseHandle(h);return ok&&n==d.size();}

FtpServer::FtpServer():listen_(INVALID_SOCKET),client_(INVALID_SOCKET),dataListen_(INVALID_SOCKET),data_(INVALID_SOCKET),cwd_("Hdd1:\\"){}
FtpServer::~FtpServer(){stop();}
void FtpServer::sendLine(const std::string&s){if(client_!=INVALID_SOCKET)send(client_,s.c_str(),s.size(),0);}
bool FtpServer::start(unsigned short port){listen_=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(listen_==INVALID_SOCKET)return false;sockaddr_in a;ZeroMemory(&a,sizeof(a));a.sin_family=AF_INET;a.sin_addr.s_addr=INADDR_ANY;a.sin_port=htons(port);if(bind(listen_,(sockaddr*)&a,sizeof(a))==SOCKET_ERROR||listen(listen_,1)==SOCKET_ERROR){stop();return false;}u_long nb=1;ioctlsocket(listen_,FIONBIO,&nb);return true;}
void FtpServer::poll(){if(listen_==INVALID_SOCKET)return;if(client_==INVALID_SOCKET){client_=accept(listen_,0,0);if(client_!=INVALID_SOCKET){u_long nb=1;ioctlsocket(client_,FIONBIO,&nb);sendLine("220 SeriesDash360 FTP ready\r\n");}return;}char b[1024];int n=recv(client_,b,sizeof(b)-1,0);if(n==0){closesocket(client_);client_=INVALID_SOCKET;closeData();return;}if(n<0)return;b[n]=0;char* cur=b;while(*cur){char* e=strpbrk(cur,"\r\n");if(e)*e=0;if(*cur)command(cur);if(!e)break;cur=e+1;while(*cur=='\r'||*cur=='\n')cur++;}}
std::string FtpServer::resolve(const std::string&p)const{if(p.empty())return cwd_;if(p.find(":\\")!=std::string::npos)return p;std::string r=cwd_;if(r.size()&&r[r.size()-1]!='\\')r+="\\";return r+p;}
bool FtpServer::openPassive(){closeData();dataListen_=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(dataListen_==INVALID_SOCKET)return false;sockaddr_in a;ZeroMemory(&a,sizeof(a));a.sin_family=AF_INET;a.sin_addr.s_addr=INADDR_ANY;a.sin_port=0;if(bind(dataListen_,(sockaddr*)&a,sizeof(a))==SOCKET_ERROR||listen(dataListen_,1)==SOCKET_ERROR){closeData();return false;}int len=sizeof(a);getsockname(dataListen_,(sockaddr*)&a,&len);unsigned short p=ntohs(a.sin_port);char line[128];sprintf(line,"227 Entering Passive Mode (127,0,0,1,%u,%u)\r\n",(unsigned)(p>>8),(unsigned)(p&255));sendLine(line);return true;}
bool FtpServer::acceptData(){if(dataListen_==INVALID_SOCKET)return false;data_=accept(dataListen_,0,0);return data_!=INVALID_SOCKET;}
void FtpServer::closeData(){if(data_!=INVALID_SOCKET){closesocket(data_);data_=INVALID_SOCKET;}if(dataListen_!=INVALID_SOCKET){closesocket(dataListen_);dataListen_=INVALID_SOCKET;}}
void FtpServer::listPath(const std::string&p){sendLine("150 Opening data connection\r\n");if(!acceptData()){sendLine("425 Cannot open data connection\r\n");return;}WIN32_FIND_DATAA fd;std::string pat=p;if(pat.size()&&pat[pat.size()-1]!='\\')pat+="\\";pat+="*";HANDLE h=FindFirstFileA(pat.c_str(),&fd);if(h!=INVALID_HANDLE_VALUE){do{if(!strcmp(fd.cFileName,".")||!strcmp(fd.cFileName,".."))continue;char l[512];sprintf(l,"%c--------- 1 xbox xbox %10lu Jan 01 2009 %s\r\n",(fd.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)?'d':'-',(unsigned long)fd.nFileSizeLow,fd.cFileName);send(data_,l,strlen(l),0);}while(FindNextFileA(h,&fd));FindClose(h);}closeData();sendLine("226 Transfer complete\r\n");}
void FtpServer::sendFile(const std::string&p){sendLine("150 Opening data connection\r\n");if(!acceptData()){sendLine("425 Cannot open data connection\r\n");return;}HANDLE h=CreateFileA(p.c_str(),GENERIC_READ,FILE_SHARE_READ,0,OPEN_EXISTING,0,0);if(h==INVALID_HANDLE_VALUE){closeData();sendLine("550 File unavailable\r\n");return;}char b[32768];DWORD n=0;bool ok=true;while(ReadFile(h,b,sizeof(b),&n,0)&&n){if(send(data_,b,n,0)<=0){ok=false;break;}}CloseHandle(h);closeData();sendLine(ok?"226 Transfer complete\r\n":"426 Transfer aborted\r\n");}
void FtpServer::receiveFile(const std::string&p){sendLine("150 Opening data connection\r\n");if(!acceptData()){sendLine("425 Cannot open data connection\r\n");return;}HANDLE h=CreateFileA(p.c_str(),GENERIC_WRITE,0,0,CREATE_ALWAYS,0,0);if(h==INVALID_HANDLE_VALUE){closeData();sendLine("550 Cannot create file\r\n");return;}char b[32768];int n;bool ok=true;while((n=recv(data_,b,sizeof(b),0))>0){DWORD w=0;if(!WriteFile(h,b,n,&w,0)||w!=(DWORD)n){ok=false;break;}}CloseHandle(h);closeData();sendLine(ok?"226 Transfer complete\r\n":"426 Transfer aborted\r\n");}
void FtpServer::command(const char* line){std::string s=line;size_t sp=s.find(' ');std::string cmd=(sp==std::string::npos)?s:s.substr(0,sp);std::string arg=(sp==std::string::npos)?"":s.substr(sp+1);for(size_t i=0;i<cmd.size();++i)cmd[i]=(char)toupper(cmd[i]);
 if(cmd=="USER")sendLine("331 Password not required\r\n");else if(cmd=="PASS")sendLine("230 Logged in\r\n");else if(cmd=="SYST")sendLine("215 XBOX360\r\n");else if(cmd=="TYPE")sendLine("200 Type set\r\n");else if(cmd=="NOOP")sendLine("200 OK\r\n");else if(cmd=="PWD")sendLine("257 \""+cwd_+"\"\r\n");else if(cmd=="CWD"){std::string p=resolve(arg);DWORD a=GetFileAttributesA(p.c_str());if(a!=INVALID_FILE_ATTRIBUTES&&(a&FILE_ATTRIBUTE_DIRECTORY)){cwd_=p;sendLine("250 Directory changed\r\n");}else sendLine("550 Directory unavailable\r\n");}else if(cmd=="PASV")openPassive();else if(cmd=="LIST"||cmd=="NLST")listPath(arg.empty()?cwd_:resolve(arg));else if(cmd=="RETR")sendFile(resolve(arg));else if(cmd=="STOR")receiveFile(resolve(arg));else if(cmd=="DELE"){sendLine(DeleteFileA(resolve(arg).c_str())?"250 Deleted\r\n":"550 Delete failed\r\n");}else if(cmd=="MKD"){sendLine(CreateDirectoryA(resolve(arg).c_str(),0)?"257 Created\r\n":"550 Create failed\r\n");}else if(cmd=="RMD"){sendLine(RemoveDirectoryA(resolve(arg).c_str())?"250 Removed\r\n":"550 Remove failed\r\n");}else if(cmd=="QUIT"){sendLine("221 Bye\r\n");closesocket(client_);client_=INVALID_SOCKET;closeData();}else sendLine("502 Command not implemented\r\n");
}
void FtpServer::stop(){closeData();if(client_!=INVALID_SOCKET){closesocket(client_);client_=INVALID_SOCKET;}if(listen_!=INVALID_SOCKET){closesocket(listen_);listen_=INVALID_SOCKET;}WSACleanup();XNetCleanup();}
}
