set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ppcbe)
if(NOT DEFINED ENV{XEDK})
  message(FATAL_ERROR "XEDK is not set.")
endif()
file(TO_CMAKE_PATH "$ENV{XEDK}" XDK_ROOT)
set(_xdk_bin "${XDK_ROOT}/bin/win32")
set(CMAKE_C_COMPILER "${_xdk_bin}/cl.exe")
set(CMAKE_CXX_COMPILER "${_xdk_bin}/cl.exe")
set(CMAKE_AR "${_xdk_bin}/lib.exe")
set(CMAKE_LINKER "${_xdk_bin}/link.exe")
set(XDK_IMAGEXEX "${_xdk_bin}/imagexex.exe" CACHE FILEPATH "XEX packager")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER_ID MSVC)
set(CMAKE_CXX_COMPILER_ID MSVC)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)
include_directories(SYSTEM "${XDK_ROOT}/include/xbox")
link_directories("${XDK_ROOT}/lib/xbox")
add_compile_definitions(_XBOX NDEBUG _MSC_VER=1300)
add_compile_options(/MT /O1 /GL /EHs-c-)
set(CMAKE_FIND_ROOT_PATH "${XDK_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
